// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcgrdwsndxjkpfgcnbhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZ3Jkd3NuZHhqa3BmZ2NuYmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDU3NDEsImV4cCI6MjA2NjE4MTc0MX0.EDNbLn1UdVAx85xv6Lh0TKGTgZX4vnzp4a-zt9qS3XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);